/*
 * This source file was generated by the Gradle 'init' task
 */
package ;

public class JavaBot {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new JavaBot().getGreeting());
    }
}
