/*
 * This source file was generated by the Gradle 'init' task
 */
package xyz.chris.discordbot;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class JavaBotTest {
    @Test
    void mainClassIsInstantiable() {
        assertDoesNotThrow(MainBot::new);
    }
}
