/*
 * This source file was generated by the Gradle 'init' task
 */
package BotTest;

import org.junit.jupiter.api.Test;

import discordbot.JavaBot;

import static org.junit.jupiter.api.Assertions.*;

class JavaBotTest {
    @Test void JavaBotHasAGreeting() {
        System.out.println("javaBotTest");
        // JavaBotTest classUnderTest = new JavaBotTest();
        // assertNotNull(classUnderTest.getGreeting(), "JavaBot should have a greeting");
    }
}
